name: study_buddy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Chewy
      fonts: 
        - asset: assets/fonts/Chewy.ttf
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arimo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arimo-SemiBoldItalic.ttf
          weight: 600
          style: italic
